sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '10'
install:
  - npm install
before_install:
  - npm i -g greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
